{{- if .Values.agent.remoteStoreBearerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: parca-agent-remote-store-bearer-token
stringData:
  token: {{ .Values.agent.remoteStoreBearerToken }}
{{- end }}
