{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parca.fullname" . }}-agent-config
  labels:
    {{- include "parca.labels.agent" . | nindent 4 }}
data:
  parca-agent.yaml: |-
{{ toYaml .Values.agent.config | indent 4 }}
{{- end }}
