{{- if and .Values.agent.enabled .Values.agent.podSecurityPolicy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "parca.labels.agent" . | nindent 4 }}
  name: {{ include "parca.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "parca.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "parca.fullname" . }}-agent
{{- end }}
