{{- if and .Values.server.enabled .Values.server.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "parca.serviceAccountName" . }}
  labels:
    {{- include "parca.labels.agent" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "parca.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "parca.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
