{{- if .Values.server.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parca.fullname" . }}
  labels:
    {{- include "parca.labels.server" . | nindent 4 }}
spec:
{{- /*
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
*/}}
  selector:
    matchLabels:
      {{- include "parca.selectorLabels.server" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "parca.selectorLabels.server" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "parca.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - /parca
            - --config-path=/var/parca/parca.yaml
            - --log-level={{ .Values.server.logLevel }}
            - --cors-allowed-origins={{ .Values.server.corsAllowedOrigins }}
            # Multiply by 1, so large integers aren't rendered in scientific notation
            - --storage-active-memory={{ mul .Values.server.storageActiveMemory 1 }}
            {{- if .Values.server.otlpAddress }}
            - --otlp-address={{ .Values.server.otlpAddress }}
            {{- end }}
            {{- if .Values.server.persistence.enabled }}
            - --enable-persistence
            - --storage-path=/data
            {{- end }}
            {{- with .Values.server.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            exec:
              command:
              - /grpc_health_probe
              - -v
              - -addr=:7070
            initialDelaySeconds: 5
          ports:
          - containerPort: 7070
            name: http
          readinessProbe:
            exec:
              command:
              - /grpc_health_probe
              - -v
              - -addr=:7070
            initialDelaySeconds: 10
          env:
            {{- with .Values.server.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          - mountPath: /var/parca
            name: {{ include "parca.fullname" . }}-server-config
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
      - configMap:
          name: {{ include "parca.fullname" . }}-server-config
        name: {{ include "parca.fullname" . }}-server-config
      {{- if .Values.server.persistence.enabled }}
      - name: data
        mountPath: /data
        emptyDir: {}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
